name: AX-Discord
version: '1.0'
main: me.aixo.axdiscord.AXDiscord
api-version: '1.19'
author: aix0
description: Plugin synchronizujący konta Minecraft z Discord

commands:
  discord:
    description: Zarządzanie integracją Discorda.
    usage: /<command> [reload]
